import React, { useState } from 'react';
import { ServerConfig, TerminalSettings } from '../types';
import { GitCompare, Database, ArrowRight, RefreshCw, FileCode, CheckCircle, AlertCircle, Layers } from 'lucide-react';

interface ERDAndSchemaDiffProps {
  servers: ServerConfig[];
  settings?: TerminalSettings;
}

interface TableSchema {
  name: string;
  columns: { name: string; type: string; isPk?: boolean; isFk?: boolean; nullable?: boolean }[];
  foreignKeys?: { column: string; targetTable: string; targetColumn: string }[];
}

export const ERDAndSchemaDiff: React.FC<ERDAndSchemaDiffProps> = ({ servers, settings }) => {
  const dbServers = servers.filter((s) => s.protocol === 'DATABASE');
  const [sourceServerId, setSourceServerId] = useState<string>(dbServers[0]?.id || '');
  const [targetServerId, setTargetServerId] = useState<string>(dbServers[1]?.id || dbServers[0]?.id || '');

  const [activeSubTab, setActiveSubTab] = useState<'ERD' | 'DIFF'>('ERD');
  const [loading, setLoading] = useState<boolean>(false);
  const [diffResult, setDiffResult] = useState<{
    addedTables: string[];
    removedTables: string[];
    modifiedTables: { name: string; addedCols: string[]; removedCols: string[] }[];
    migrationScript: string;
  } | null>(null);

  // Mock schema representation for visual ERD & Diffing
  const mockSourceTables: TableSchema[] = [
    {
      name: 'users',
      columns: [
        { name: 'id', type: 'INT', isPk: true },
        { name: 'username', type: 'VARCHAR(100)' },
        { name: 'email', type: 'VARCHAR(255)' },
        { name: 'password_hash', type: 'VARCHAR(255)' },
        { name: 'created_at', type: 'TIMESTAMP' }
      ]
    },
    {
      name: 'orders',
      columns: [
        { name: 'id', type: 'INT', isPk: true },
        { name: 'user_id', type: 'INT', isFk: true },
        { name: 'total_amount', type: 'DECIMAL(10,2)' },
        { name: 'status', type: 'VARCHAR(50)' },
        { name: 'created_at', type: 'TIMESTAMP' }
      ],
      foreignKeys: [{ column: 'user_id', targetTable: 'users', targetColumn: 'id' }]
    },
    {
      name: 'order_items',
      columns: [
        { name: 'id', type: 'INT', isPk: true },
        { name: 'order_id', type: 'INT', isFk: true },
        { name: 'product_id', type: 'INT' },
        { name: 'quantity', type: 'INT' },
        { name: 'price', type: 'DECIMAL(10,2)' }
      ],
      foreignKeys: [{ column: 'order_id', targetTable: 'orders', targetColumn: 'id' }]
    }
  ];

  const handleRunCompare = () => {
    setLoading(true);
    setTimeout(() => {
      setDiffResult({
        addedTables: ['audit_logs', 'notifications'],
        removedTables: ['legacy_sessions'],
        modifiedTables: [
          {
            name: 'users',
            addedCols: ['two_factor_secret VARCHAR(64)', 'last_login_at TIMESTAMP'],
            removedCols: ['temp_token']
          },
          {
            name: 'orders',
            addedCols: ['discount_code VARCHAR(50)'],
            removedCols: []
          }
        ],
        migrationScript: `-- Migration Script Generated by OmniTerminal Schema Diff
-- Source: ${servers.find((s) => s.id === sourceServerId)?.name || 'Dev DB'}
-- Target: ${servers.find((s) => s.id === targetServerId)?.name || 'Staging DB'}

-- 1. Create New Tables
CREATE TABLE audit_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    action VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE
);

-- 2. Modify Existing Tables
ALTER TABLE users ADD COLUMN two_factor_secret VARCHAR(64) NULL;
ALTER TABLE users ADD COLUMN last_login_at TIMESTAMP NULL;
ALTER TABLE users DROP COLUMN temp_token;

ALTER TABLE orders ADD COLUMN discount_code VARCHAR(50) NULL;

-- 3. Drop Removed Tables
DROP TABLE IF EXISTS legacy_sessions;
`
      });
      setLoading(false);
    }, 1000);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: 'var(--bg-primary)', padding: '20px', overflowY: 'auto' }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '20px' }}>
        <div>
          <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <GitCompare size={22} style={{ color: 'var(--accent-primary)' }} />
            <span>Trình Thiết Kế Sơ Đồ ERD & Schema Diff</span>
          </h2>
          <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>
            Xem sơ đồ quan hệ cơ sở dữ liệu (Visual ERD) và so sánh sự khác biệt cấu trúc giữa 2 môi trường để sinh script Migration tự động.
          </p>
        </div>

        {/* Sub-tab Navigation */}
        <div style={{ display: 'flex', backgroundColor: 'var(--bg-secondary)', padding: '4px', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border-subtle)' }}>
          <button
            onClick={() => setActiveSubTab('ERD')}
            style={{
              padding: '6px 16px',
              borderRadius: '4px',
              border: 'none',
              backgroundColor: activeSubTab === 'ERD' ? 'var(--accent-primary)' : 'transparent',
              color: activeSubTab === 'ERD' ? '#fff' : 'var(--text-muted)',
              fontSize: '0.8rem',
              fontWeight: 600,
              cursor: 'pointer'
            }}
          >
            Trực Quan Sơ Đồ ERD
          </button>
          <button
            onClick={() => setActiveSubTab('DIFF')}
            style={{
              padding: '6px 16px',
              borderRadius: '4px',
              border: 'none',
              backgroundColor: activeSubTab === 'DIFF' ? 'var(--accent-primary)' : 'transparent',
              color: activeSubTab === 'DIFF' ? '#fff' : 'var(--text-muted)',
              fontSize: '0.8rem',
              fontWeight: 600,
              cursor: 'pointer'
            }}
          >
            So Sánh Cấu Trúc (Schema Diff)
          </button>
        </div>
      </div>

      {activeSubTab === 'ERD' ? (
        /* Visual ERD Diagram View */
        <div style={{ flex: 1, backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)', padding: '20px', display: 'flex', flexDirection: 'column' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
            <label style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Chọn CSDL xem ERD:</label>
            <select
              className="input-field"
              value={sourceServerId}
              onChange={(e) => setSourceServerId(e.target.value)}
              style={{ width: '260px', height: '34px', fontSize: '0.82rem' }}
            >
              {dbServers.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name} ({s.dbType})
                </option>
              ))}
            </select>
          </div>

          <div style={{ flex: 1, display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '20px', alignItems: 'start' }}>
            {mockSourceTables.map((table) => (
              <div
                key={table.name}
                style={{
                  backgroundColor: 'var(--bg-tertiary)',
                  border: '1px solid var(--accent-primary)',
                  borderRadius: 'var(--radius-sm)',
                  boxShadow: 'var(--shadow-md)',
                  overflow: 'hidden'
                }}
              >
                <div style={{ backgroundColor: 'rgba(59, 130, 246, 0.2)', padding: '8px 12px', fontWeight: 700, fontSize: '0.85rem', color: 'var(--text-main)', borderBottom: '1px solid var(--border-subtle)', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Layers size={14} style={{ color: 'var(--accent-primary)' }} />
                  <span>{table.name}</span>
                </div>
                <div style={{ padding: '8px 12px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
                  {table.columns.map((col) => (
                    <div key={col.name} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.78rem', color: 'var(--text-main)' }}>
                      <span>
                        {col.isPk && <strong style={{ color: 'var(--accent-warning)', marginRight: '4px' }}>🔑</strong>}
                        {col.isFk && <strong style={{ color: 'var(--accent-success)', marginRight: '4px' }}>🔗</strong>}
                        {col.name}
                      </span>
                      <span style={{ color: 'var(--text-dim)', fontSize: '0.72rem' }}>{col.type}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      ) : (
        /* Schema Diff & Migration Script View */
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <div style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)', padding: '16px', display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ flex: 1 }}>
              <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>CSDL Nguồn (Source - Dev):</label>
              <select className="input-field" value={sourceServerId} onChange={(e) => setSourceServerId(e.target.value)} style={{ height: '36px', fontSize: '0.82rem' }}>
                {dbServers.map((s) => (
                  <option key={s.id} value={s.id}>{s.name} ({s.environment})</option>
                ))}
              </select>
            </div>

            <ArrowRight size={20} style={{ color: 'var(--accent-primary)', marginTop: '20px' }} />

            <div style={{ flex: 1 }}>
              <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>CSDL Đích (Target - Staging/Prod):</label>
              <select className="input-field" value={targetServerId} onChange={(e) => setTargetServerId(e.target.value)} style={{ height: '36px', fontSize: '0.82rem' }}>
                {dbServers.map((s) => (
                  <option key={s.id} value={s.id}>{s.name} ({s.environment})</option>
                ))}
              </select>
            </div>

            <button className="btn-primary" onClick={handleRunCompare} disabled={loading} style={{ height: '36px', marginTop: '20px', padding: '0 20px' }}>
              {loading ? <RefreshCw size={14} className="spin" /> : <GitCompare size={14} />}
              <span>{loading ? 'Đang So Sánh...' : 'So Sánh Schema Diff'}</span>
            </button>
          </div>

          {diffResult && (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              {/* Diff Summary Cards */}
              <div style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)', padding: '16px' }}>
                <h3 style={{ fontSize: '0.95rem', fontWeight: 600, color: 'var(--text-main)', marginBottom: '12px' }}>
                  📊 Tóm Tắt Sự Khác Biệt Cấu Trúc
                </h3>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', fontSize: '0.8rem' }}>
                  <div style={{ backgroundColor: 'rgba(34, 197, 94, 0.1)', border: '1px solid rgba(34, 197, 94, 0.3)', padding: '10px', borderRadius: '4px', color: 'var(--accent-success)' }}>
                    <strong>+ Bảng Mới Thêm Vào ({diffResult.addedTables.length}):</strong> {diffResult.addedTables.join(', ')}
                  </div>

                  <div style={{ backgroundColor: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.3)', padding: '10px', borderRadius: '4px', color: 'var(--accent-danger)' }}>
                    <strong>- Bảng Bị Xóa ({diffResult.removedTables.length}):</strong> {diffResult.removedTables.join(', ')}
                  </div>

                  <div style={{ backgroundColor: 'rgba(245, 158, 11, 0.1)', border: '1px solid rgba(245, 158, 11, 0.3)', padding: '10px', borderRadius: '4px', color: 'var(--accent-warning)' }}>
                    <strong>⚡ Bảng Có Cấu Trúc Thay Đổi ({diffResult.modifiedTables.length}):</strong>
                    <ul style={{ marginTop: '6px', paddingLeft: '20px' }}>
                      {diffResult.modifiedTables.map((m) => (
                        <li key={m.name}>
                          <strong>{m.name}</strong>: +[{m.addedCols.join(', ')}] -[{m.removedCols.join(', ')}]
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>

              {/* Migration Script Viewer */}
              <div style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)', padding: '16px', display: 'flex', flexDirection: 'column' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                  <span style={{ fontSize: '0.95rem', fontWeight: 600, color: 'var(--text-main)', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <FileCode size={16} style={{ color: 'var(--accent-primary)' }} />
                    <span>Script Migration SQL Tự Động</span>
                  </span>
                  <button
                    className="btn-secondary"
                    onClick={() => navigator.clipboard.writeText(diffResult.migrationScript)}
                    style={{ height: '28px', fontSize: '0.72rem' }}
                  >
                    Copy Script
                  </button>
                </div>
                <textarea
                  readOnly
                  value={diffResult.migrationScript}
                  style={{
                    flex: 1,
                    minHeight: '220px',
                    backgroundColor: 'var(--bg-tertiary)',
                    color: '#a7f3d0',
                    fontFamily: 'monospace',
                    fontSize: '0.78rem',
                    border: '1px solid var(--border-subtle)',
                    borderRadius: 'var(--radius-sm)',
                    padding: '12px',
                    resize: 'none'
                  }}
                />
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
